In [26]:
import sympy
from sympy import cos, sin
import numpy as np
sympy.init_printing()

In [6]:
X, Y, A = sympy.symbols("X Y A")
x, y, a = sympy.symbols("x y a")
x1, y1, a1 = sympy.symbols("x_1 y_1 a_1")

In [9]:
def transform_matrix(x, y, a):
    return sympy.Matrix([[cos(a), -sin(a), x], [sin(a), cos(a), y], [0, 0, 1]])

In [10]:
Ml = transform_matrix(x, y, a)
Mg = transform_matrix(x1, y1, a1)
Mgl = transform_matrix(X, Y, A)

In [14]:
sympy.simplify(Mgl * Ml)

⎡cos(A + a)  -sin(A + a)  X + x⋅cos(A) - y⋅sin(A)⎤
⎢                                                ⎥
⎢sin(A + a)  cos(A + a)   Y + x⋅sin(A) + y⋅cos(A)⎥
⎢                                                ⎥
⎣    0            0                  1           ⎦

In [23]:
sympy.simplify(Mg * sympy.simplify(Ml.inv()))

⎡cos(a - a₁)   sin(a - a₁)  -x⋅cos(a - a₁) + x₁ - y⋅sin(a - a₁)⎤
⎢                                                              ⎥
⎢-sin(a - a₁)  cos(a - a₁)  x⋅sin(a - a₁) - y⋅cos(a - a₁) + y₁ ⎥
⎢                                                              ⎥
⎣     0             0                        1                 ⎦

In [24]:
sympy.simplify(sympy.simplify(Mgl.inv()) * Mg)

⎡cos(A - a₁)   sin(A - a₁)  -X⋅cos(A) - Y⋅sin(A) + x₁⋅cos(A) + y₁⋅sin(A)⎤
⎢                                                                       ⎥
⎢-sin(A - a₁)  cos(A - a₁)  X⋅sin(A) - Y⋅cos(A) - x₁⋅sin(A) + y₁⋅cos(A) ⎥
⎢                                                                       ⎥
⎣     0             0                            1                      ⎦

In [50]:
a = np.arange(54).reshape(9, 3, 2)

In [51]:
ind = np.random.randint(0, 3, (9, 5))

In [52]:
ind

array([[0, 2, 0, 0, 1],
       [2, 1, 0, 2, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 1, 2],
       [2, 1, 2, 2, 0],
       [1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [2, 0, 1, 0, 2],
       [1, 1, 1, 0, 2]])

In [53]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39],
        [40, 41]],

       [[42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53]]])

In [54]:
a[np.arange(9).reshape(9, 1), ind]

array([[[ 0,  1],
        [ 4,  5],
        [ 0,  1],
        [ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [ 8,  9],
        [ 6,  7],
        [10, 11],
        [ 6,  7]],

       [[12, 13],
        [14, 15],
        [12, 13],
        [12, 13],
        [14, 15]],

       [[18, 19],
        [20, 21],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[28, 29],
        [26, 27],
        [28, 29],
        [28, 29],
        [24, 25]],

       [[32, 33],
        [32, 33],
        [30, 31],
        [32, 33],
        [32, 33]],

       [[36, 37],
        [36, 37],
        [36, 37],
        [38, 39],
        [38, 39]],

       [[46, 47],
        [42, 43],
        [44, 45],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [50, 51],
        [50, 51],
        [48, 49],
        [52, 53]]])

In [46]:
a[:, ind]

array([[[ 1,  0,  0],
        [ 0,  0,  1],
        [ 1,  0,  0],
        [ 1,  1,  1],
        [ 1,  0,  0],
        [ 1,  0,  0],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 0,  1,  0]],

       [[ 3,  2,  2],
        [ 2,  2,  3],
        [ 3,  2,  2],
        [ 3,  3,  3],
        [ 3,  2,  2],
        [ 3,  2,  2],
        [ 3,  3,  3],
        [ 3,  3,  3],
        [ 2,  3,  2]],

       [[ 5,  4,  4],
        [ 4,  4,  5],
        [ 5,  4,  4],
        [ 5,  5,  5],
        [ 5,  4,  4],
        [ 5,  4,  4],
        [ 5,  5,  5],
        [ 5,  5,  5],
        [ 4,  5,  4]],

       [[ 7,  6,  6],
        [ 6,  6,  7],
        [ 7,  6,  6],
        [ 7,  7,  7],
        [ 7,  6,  6],
        [ 7,  6,  6],
        [ 7,  7,  7],
        [ 7,  7,  7],
        [ 6,  7,  6]],

       [[ 9,  8,  8],
        [ 8,  8,  9],
        [ 9,  8,  8],
        [ 9,  9,  9],
        [ 9,  8,  8],
        [ 9,  8,  8],
        [ 9,  9,  9],
        [ 9,  9,  9],
        [ 8,  9,  8]],

